### ISSUE TITLE
Release builded file?

### ISSUE THREAD

**Issue by Zenedith** [SWRT-dev/ac85p-asuswrt#1]
Could you release builded file?

**Comment by paldier** [comment]
firmware?

**Comment by Zenedith** [comment]
Yes, firmware. Any issues with it?

**Comment by mlpzaq9998** [comment]
能否补全缺失的文件？

**Comment by paldier** [comment]
this code seems to be the code of ac85u,and webui has some bugs
`/tmp$ uname -a
Linux RT-AC85P 3.10.14 #15 SMP Mon Feb 10 15:15:25 CST 2020 mips ASUSWRT`
mtk is mipsle not mips
