### ISSUE TITLE
SmartDNS配置問題

### ISSUE THREAD

**Issue by berlaychen** [SWRT-dev/ac85p-asuswrt#14]
您好 近日刷入了大神提供的
梅林5.1.4 但部分網站會不能使用
研判是DNS的問題 因為改了海外DNS短暫可以用
 
![image](https://user-images.githubusercontent.com/51433626/119889677-77f5c980-bf69-11eb-8007-82a450ac21e7.png)

有在etc/smartdns.conf更改dns了 但只要終止進程在打開 又會變成預設的中國DNS
請問這個要如何解決呢?謝謝!

**Comment by paldier** [comment]
国行永久使用中国dns，不可更改

**Comment by berlaychen** [comment]
那有辦法關閉smartdns的sercixe嗎？

**Comment by paldier** [comment]
国外不要买国行产品

**Comment by berlaychen** [comment]
所以目前海外沒辦關閉smartdns是嗎？

**Comment by paldier** [comment]
国外不要买国行产品
