### ISSUE TITLE
Duplicates in the list of supported nand flash

### ISSUE THREAD

**Issue by kilroy98** [SWRT-dev/ac85p-asuswrt#15]
These are duplicate entries, or I'm wrong? (On lines 20-21)

https://github.com/SWRT-dev/ac85p-asuswrt/blob/96a4ff1161d26e513eccc2a08628699241cbc9dd/release/src-ra-5010/linux/linux-3.10.14.x/drivers/mtd/nand/nand_device_list.h#L9-L10

and

https://github.com/SWRT-dev/ac85p-asuswrt/blob/96a4ff1161d26e513eccc2a08628699241cbc9dd/release/src-ra-5010/linux/linux-3.10.14.x/drivers/mtd/nand/nand_device_list.h#L20-L21

And I have one more question, can you make a new build for RMAC2100 with all the latest changes? Unfortunately, I am not able to do it myself :(

P.S. Sorry for my english, i use google translate.

**Comment by paldier** [comment]
very soon
