### ISSUE TITLE
Some questions about translations

### ISSUE THREAD

**Issue by kilroy98** [SWRT-dev/ac85p-asuswrt#17]
Main_Soft_center.asp and Tools_Sysinfo.asp support translation? Because I could not find in which file their translations are located. On Main_Soft_center.asp when selected any other language it shows chinesi symbols.
And when any other language is selected, instead of the item names in the side menu, it shows "English".
![1](https://user-images.githubusercontent.com/13346898/125913080-f1bae15d-e6b4-4bf6-ab8a-a106a4180e3c.png)
![2](https://user-images.githubusercontent.com/13346898/125912850-ab49d726-0bc9-4445-8d21-0871c32bc80d.png)

And i found one bug with Main_Soft_center.asp . When you are on the Main_Soft_center.asp page, it is not possible to change the language. A drop down list appears, but nothing happens when I click on any language.

Firmware version: 5.1.1 (Maybe this bug is fixed on last versions, but I can't update the firmware, because I have a shitty Toshiba Nand Flash with bad blocks, and when i try to update firmware via Breed, router reboots and never boot, leds turn off and nothing happens. And I don't have UART adapter to provide logs).
kernel: Bad eraseblock 14 at 0x0000001c0000
kernel: Bad eraseblock 15 at 0x0000001e0000
kernel: Bad eraseblock 768 at 0x000006000000

Sorry for asking questions through issues.

**Comment by paldier** [comment]
Announcement information only supports Chinese and English.

I guess the reason is that rootfs is not mounted properly. I fix this issue in 5.1.6.

**Comment by kilroy98** [comment]
Can you make a test build with this fix for me?

**Comment by kilroy98** [comment]
@paldier Hi, have you fixed the problem with writing firmware in version 5.1.6?

**Comment by kilroy98** [comment]
@paldier Hi, have you fixed the problem with writing firmware? :(
If need i may give you full flash dump made from Breed, maybe it help you to fix this problem.
