### ISSUE TITLE
Please add more "Region" choices

### ISSUE THREAD

**Issue by starix** [SWRT-dev/ac85p-asuswrt#7]
Firmware has 4 regions to choose in WiFi settings: Asia, China, Singapore, Australia. Please add more regional settings. At least Russian, Europe, America. More is better. Thank you.

**Comment by paldier** [comment]
The ASUS does not allow to add more regions.

**Comment by ferhung-mtk** [comment]
No, regions can be choosed by setting "rc_support("loclist")". 
But more changing should be add to core. (RELATED TO "init-ralink.c"and "rt_channel.c", and so on.)
Maybe, i will release them after a few days.

**Comment by paldier** [comment]
no,you must change all prebuild files of rc&shared&httpd and webui(html, js)

**Comment by ferhung-mtk** [comment]
lukasz1992 used these two commits:
https://github.com/lukasz1992/asuswrt-xiaomi/commit/7275cd850a6dbc7f104d6fa0bad54ad00db9417d
https://github.com/lukasz1992/asuswrt-xiaomi/commit/644dd9077bdd0621d09218e4d17f14a0c710182f
In my method, it dose not need to reset the location list in init-ralink.c, just use "nvram_get("location_code")", then make wl_country_code to follow this location_code.
